### ISSUE TITLE
Error in contentscript from kango invoke async

### ISSUE THREAD

**Issue by dharma-guardian** [iamolivinius/gulpicRose#5]
```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'response' of undefined
    at chrome-extension://bphiaglkmhjpneddlpjfhohmjdgfalba/includes/content.js:126:178
    at Object.d.onSuccess (chrome-extension://bphiaglkmhjpneddlpjfhohmjdgfalba/includes/content.js:106:7)
    at Object.v [as KangoInvokeAsyncModule_result] (chrome-extension://bphiaglkmhjpneddlpjfhohmjdgfalba/includes/content.js:74:52)
    at Array.<anonymous> (chrome-extension://bphiaglkmhjpneddlpjfhohmjdgfalba/includes/content.js:90:13)
    at chrome-extension://bphiaglkmhjpneddlpjfhohmjdgfalba/includes/content.js:141:225
```
Object.d.onSuccess is https://github.com/iamolivinius/gulpicRose/blob/master/kango/src/js/common/kango/invoke_async.js#L90

**Comment by iamolivinius** [comment]
Downgrade to localforage 0.9.2 fixed this
